[project]
name = 'Volunteer-Hour-Tracking-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.organization-verification]
path = 'contracts/organization-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.volunteer-registration]
path = 'contracts/volunteer-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
